# Dependencies
markdown:         kramdown
pygments:         true
highlighter:      rouge

# Permalinks
permalink:        /:year/:month/:title

# Setup
title:            Jinx
tagline:          432hz
url:              http://jinx432.github.io
paginate:         10
baseurl:          /
author:
  name:           Jinx
  url:            https://twitter.com/jinx_______
  email:          jinx.wyvern@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/jinx432/jinx432.github.io
