# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Shitposter
tagline:          ™
description:      Madam, I have come from a country where people are hanged if they talk ~ Leonhard Euler
url:              http://shitposter.ca
paginate:         10
baseurl:          http://shitposter.ca/
image_url:        http://shitposter.ca/img/
author:
  name:           Jinx
  url:            https://twitter.com/wyvern_jinx
  email:          jinx.wyvern@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/jinx432/jinx432.github.io
