# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Hivegreen
tagline:          Cargo container architecture
description:      Cargo container architecture. It's super cheap, compact and eco-friendly.
url:              http://hivegreen.com/blog
paginate:         5
baseurl:          http://hivegreen.com/
image_url:        http://hivegreen.com/img/
author:
  name:           Jinx
  url:            https://twitter.com/hivegrn
  email:          hivegreen.info@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/LeighAkin/blog
