# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Jinx
tagline:          shitpost
description:      Madam, I have come from a country where people are hanged if they talk ~ Leonhard Euler
url:              https://jinx432.github.io
paginate:         10
baseurl:          https://jinx432.github.io/
image_url:        http://jinx432.com/img/
author:
  name:           Jinx
  url:            https://twitter.com/jinx_______
  email:          jinx.wyvern@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/jinx432/jinx432.github.io
